# Improve colors
set -g default-terminal 'screen-256color'

set-option -sa terminal-overrides ",xterm*:Tc"

# Set scrollback buffer to 10000
set -g history-limit 10000

# set -g status-justify left
# set -g status-position top
# set -g status-left-length 200
# set -g status-right-length 200

# set the starting index for windows and panes to 1
set -g base-index 1
set -g extended-keys on
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Customize the status line
# set -g status-fg  green
# set -g status-bg  black

set-option -sg escape-time 10
set-option -g focus-events on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on

# Shift + Alt + H/L to move windows left and right
bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark256'

run '~/.tmux/plugins/tpm/tpm'
